### ISSUE TITLE
Pass the time.Duration directly to Parse?

### ISSUE THREAD

**Issue by ammario** [hako/durafmt#1]
It seems like with the current API a common pattern would arise:

```go
var dur time.Duration
...
if d, err := durafmt.Parse(dur.String()); err != nil {
    check(err)
}
```

Passing it directly it becomes:
```go
var dur time.Duration
...
d := durafmt.Parse(dur)
```

And allows for this chain:
```go
str := durafmt.Parse(dur).String()
```

**Comment by hako** [comment]
I like the idea, I think durafmt should also parse both `string` and `time.Duration`, So something like:

+ `durafmt.Parse` for `time.Duration`
+ `durafmt.FromString` for Go strings.

**Comment by hako** [comment]
`durafmt.Parse` now accepts time.Duration instead of string. Added in https://github.com/hako/durafmt/commit/9b9c09548c8914af38893cf389c40da2a8d8f2e9
