### ISSUE TITLE
durafmt incorrectly calculates the duration.

### ISSUE THREAD

**Issue by adewale** [hako/durafmt#2]
As you can see from this gist: https://gist.github.com/adewale/da804cc1db00c26e4892eb0da6463789 durafmt incorrectly calculates the duration in some scenarios.

A duration that should be "1 year 1 day" becomes "1 year 1 month 3 days"

**Comment by adewale** [comment]
After thinking about this more (and with a nudge from Tom Insam on Twitter: https://twitter.com/tominsam/status/737849740168073217 ) I've realised that this problem can't be solved (with the current implementation and design) for the following units:
- days: days aren't always 24 hours long because of daylight savings.
- weeks: weeks aren't always 168 hours long because days aren't always 24 hours long.
- months: months aren't always 4 weeks long. February is 4 weeks long 3 out of every 4 years. The others are all longer than 4 weeks.
- years: the code currently assumes that years are 48 weeks long and the tests hardcode an incorrect value for the numbers of hours in a year. There are 8760 in a 52 week year since years aren't 4*12 weeks long.

The above are why time.Duration: https://golang.org/pkg/time/#Duration doesn't handle any unit larger than hours.

One way to surface these issues is to add the following lines to the TestParse function in durafmt_test.go
`		{8760 * time.Hour, "1 year"},
		{17520 * time.Hour, "2 years"},` 

One workaround might be to remove the formatting of any unit larger than an hour.

**Comment by hako** [comment]
Resolved in https://github.com/hako/durafmt/commit/83a6d8dc879e5db09185e352561da4326f443de6
