### ISSUE TITLE
i18n duration formatting

### ISSUE THREAD

**Issue by fat0troll** [hako/durafmt#23]
Is there any interest for internationalised (non-English) duration formatting? I've created https://github.com/fat0troll/durufmt for Russian language, based on your library (thank you!), and I'm curious is there a need for fully-internationalised time duration formatting library?

Maybe someone will create it's own implementation or figure out, how to implement i18n in durafmt directly.

And again, thanks for your library, it's awesome (but I needed one for Russian language, so I created one based on your work)!

**Comment by hako** [comment]
Hey @fat0troll, thanks and glad you found durafmt useful with durufmt!

i18n support for durafmt would be a great feature. Like with your russian fork, some languages work differently to english. So durafmt would need to be restructured to accommodate more languages.

**Comment by fat0troll** [comment]
I'll try to think about ways to restructure durafmt for full i18n in my spare time :)

**Comment by hako** [comment]
@fat0troll PR #26 includes support for custom languages, it may be worth looking into if the Russian language can be supported.
