### ISSUE TITLE
Return nil pointer from ParseString() called with invalid argument

### ISSUE THREAD

**Issue by koorgoo** [hako/durafmt#3]
It is better to return a `nil` pointer when invalid string is passed to `ParseString()`, because calling `Durafmt.String()` has no sense in this case (runtime error).

```go
// Expected behavior.
d, err := durafmt.ParseString("invalid")
fmt.Println(err != nil) // true
fmt.Println(d == nil)   // true
```

**Comment by hako** [comment]
Fixed in https://github.com/hako/durafmt/commit/b684ad4c820a261e028ccbf4a332d64b33b883b5. Thanks!
